### ISSUE TITLE
Comparison to MPF solutions such as BBHash

### ISSUE THREAD

**Issue by mpetri** [bitwiseshiftleft/frayed_cascade#1]
How would this crate compare to approaches such as BBHash https://github.com/rizkg/BBHash

This works really well in practice and from a space usage perspective is also quite nice.

**Comment by bitwiseshiftleft** [comment]
Good question. I’m mostly a cryptographer and not a data structures expert but here’s my understanding.

The traditional use of a minimal perfect hash to build a static function is a good approach if the outputs have high entropy.  It’s also good for cases where you’re more focused on storage instead of distribution so you don’t value compression as much, or for cases where you want to update the values (but not the keys) on the fly.

This crate is optimized for the case where you really want to compress, and the outputs have low entropy, so that paying 2-3 bits per key hurts the compression ratio. In an extreme case like the CRL example, the map has about 0.06 bits of entropy per key, so using an MPH and then a table basically wouldn’t work.

There’s probably also a good route of MPH -> approximate sets -> static functions, but I haven’t done the math in how that compares. Going from approximate sets to static functions instead of vice versa does introduce an overhead though (this is what CRLite does).  Maybe there are other good approaches along these lines too.

In the other direction, this crate definitely won’t scale like BBHash.  It may be worth eventually adding alternative mechanisms for eg larger maps where frayed ribbons won’t scale (eg binary fuse filters are about 10x faster to construct, probably comparable to query, and use about 10% more space; or you could shard the maps from this crate), or maps where the values have high entropy, or where you can estimate the value from the key, etc.

**Comment by bitwiseshiftleft** [comment]
Actually I shouldn’t say BFFs are likely slower to query: there are a lot of factors one way or the other, but anyway they both have fast queries.
